### ISSUE TITLE
express 中middleware

### ISSUE THREAD

**Issue by jiaojiaojiao** [peaksnail/pinpoint-node-agent#16]
hi,你们如何监控中间键里面的服务的呢

**Comment by peaksnail** [comment]
目前我们用到router，cookie-parse中间件，实际上只监控了router相关逻辑，通过参数req传递traceContext 相关跟踪数据，然后改写业务逻辑处理函数。

在express中，从请求开始到结束，相关中间件，业务逻辑处理函数中都会有 req，res 两个参数，能否从这个角度考虑下，这样 直接改写中间件处理函数，一个是从traceContextFactory获取上下文，如果获取失败，可以从req参数中获取，同时保存到req参数中，方便后面的调用栈获取。

**Comment by jiaojiaojiao** [comment]
嗯嗯，现在就是只能通过类似这种express.application.handle函数，去处理中间件里面调用的服务，感觉不是太好，因为还要屏蔽静态资源

**Comment by peaksnail** [comment]
对啊，之前看过源码，没发现什么好的方法，所以这样处理了，在express 插件中，提供了对静态资源的过滤
