### ISSUE TITLE
Full gc一直存在

### ISSUE THREAD

**Issue by jiaojiaojiao** [peaksnail/pinpoint-node-agent#18]
![image](https://cloud.githubusercontent.com/assets/16285633/21387863/a753e272-c7b4-11e6-8858-542cbd08219d.png)
所有接入的node应用下，每个请求都会出现full gc，这个是什么信息，为什么一直存在

**Comment by peaksnail** [comment]
pinpoint 原生是适用于java的，所以full gc是针对java应用的。node agent这里并没有设置full gc相关的数据，有关full gc的数据都设置为0。
之所以出现 可能和采集周期有关，和请求没有关系。所以对于node应用，full gc数据可以忽略

java full gc时，应用会停止一切响应，等垃圾回收后再响应。此时agent 无法发送相关监控信息给collector，在这一个时间周期中，collector没有收到任何监控信息，认为可能出现了full gc。具体代码还没有阅读过，这是个人猜测可能的原因。
