### ISSUE TITLE
writeString/writeBinary called without a string/Buffer

### ISSUE THREAD

**Issue by flashtintin** [peaksnail/pinpoint-node-agent#21]
![default](https://cloud.githubusercontent.com/assets/26218080/23602835/56f29b84-028d-11e7-8d0a-abec6a1c8f25.png)

请问一下，项目启动后一直报这个错误。
我使用的是Express4，node的版本是4.4.1。
用脚手架搭的Express，require('./modules/pinpoint-node-agent');写在app.js里，而不是bin/www里面，有影响吗？

**Comment by peaksnail** [comment]
只要在启动入口文件的第一行写入require(${pinpoint-node-agent-path}) 即可，
参考错误信息，看下agent 配置是否有误

**Comment by flashtintin** [comment]
我用的默认配置，只修改了id、name、profiler.collector.ip三项……

**Comment by peaksnail** [comment]
报错显示传了参数 数字8？ id或者name为string类型

2017-03-08 9:48 GMT+08:00 flashtintin <notifications@github.com>:

**Comment by flashtintin** [comment]
果然是写错了参数类型，谢谢
