### ISSUE TITLE
在应用启动的时候，探针框架中直接把所有的require的模块，存在一个变量havaloaded引起bug

### ISSUE THREAD

**Issue by jiaojiaojiao** [peaksnail/pinpoint-node-agent#22]
在应用启动的时候，探针框架中直接把所有的require的模块，存在一个变量havaloaded中，当我手动去定时重新生成新的文件的时候，应用还是调用我保存在havaloaded的文件，而不是新生成的文件，
![image](https://cloud.githubusercontent.com/assets/16285633/23787499/66358d22-05ad-11e7-95f5-0e5c41da54e9.png)
所以是不是应该只保存我去wrap的模块，其他的模块不去保存
![image](https://cloud.githubusercontent.com/assets/16285633/23787660/05915b3a-05ae-11e7-9d4c-bda362f834af.png)

**Comment by peaksnail** [comment]
在你说的这种动态加载的场景中确实存在这种问题，可以先把缓存去掉
