### ISSUE TITLE
pinpoint web 端nodejs应用fullgc数据为1

### ISSUE THREAD

**Issue by jiaojiaojiao** [peaksnail/pinpoint-node-agent#24]
nodejs应用fullgc数据传值为0，可是web端展示为1，如下图
![image](https://cloud.githubusercontent.com/assets/16285633/24501059/88305b1e-157a-11e7-9488-c3b9290db173.png)
![image](https://cloud.githubusercontent.com/assets/16285633/24501086/a6c77116-157a-11e7-8994-570efd875601.png)
这样很容易误导用户

**Comment by peaksnail** [comment]
嗯，现在就是初始化设置为0，但是web端为什么如此显示还不清楚，你这边可以先试下初始化设置为null看下。后续我这边再看下代码

**Comment by jiaojiaojiao** [comment]
我试了传0，null都会显示1，这个是不是后端直接处理的

**Comment by peaksnail** [comment]
嗯，agent传输给collector存储，然后web拉取数据显示。可能是collector或者web逻辑导致的
