### ISSUE TITLE
nodeagent怎么看请求/应答分布图表和callstack

### ISSUE THREAD

**Issue by beastzrj** [peaksnail/pinpoint-node-agent#25]
右边只有response summary 和  load

**Comment by peaksnail** [comment]
不管是何种agent，查看trace信息方法都是一样的。具体 可以参考下 [pinpoint官方说明](https://github.com/naver/pinpoint)，需要用鼠标圈选 具体请求的点

**Comment by beastzrj** [comment]
恩，搞定了，谢谢
