### ISSUE TITLE
生成Java代码报错

### ISSUE THREAD

**Issue by wunengbiao** [peaksnail/pinpoint-node-agent#31]
deploy

pinpoint is developed by java,so you should convert the node plugin to java plugin(the web will show some undefined value if you don't use the relative java plugin)

cd pinpoint/agent/utils/tools && node java_code_generator.js ${pluginName}

it will generate the java plugin directory,and then compile it with maven.Finally you can use the war file deployed in collector and web module.

你好，按照你的方法生成java代码报错啊？？

**Comment by peaksnail** [comment]
报什么错？log？
