### ISSUE TITLE
getNextSpanId问题

### ISSUE THREAD

**Issue by jiaojiaojiao** [peaksnail/pinpoint-node-agent#8]
pinpoint-node-agent/agent/common/trace/span_recorder文件中，去设置获取nextSpanId，我这边和后端dubbo连接起来需要传这个id，应该是唯一标记某个请求的，但是发现nextSpanId在一个span下面的多个spanevent是一样的值。
```
SpanRecorder.prototype.getNextSpanId = function getNextSpanId() {
    if (this.nextSpanId === undefined) {
        this.nextSpanId = SequenceNumberSingleton.getSequenceNumber();
    }
    return this.nextSpanId;
};
```

**Comment by peaksnail** [comment]
是这样的，一个请求是由不同span组成的（比如某个请求涉及到前端spanId－A，后端spanId－B），每个span由spanId唯一标识，整个请求由唯一transactionId 标识。然后 一个span下有多个spanEvent表示调用的函数链。所以会看到同属一个span的spanEvent的nextSpanId是一样的。

**Comment by jiaojiaojiao** [comment]
额,但是我请求就是前端发出去的某个请求a，可能发出多个后端接口请求，这样的话不就是我前端的一个请求span－a，下面有多个spanevent记录不同请求的函数链（http请求，dubbo请求，https请求等），那这样我怎么和请求后端的多个接口建立连接呢

**Comment by peaksnail** [comment]
通过transactionId 来标识 整个完整的请求的。是需要将transactionId 传递下去的

**Comment by jiaojiaojiao** [comment]
嗯嗯，那这样的话是属于我一个前端请求只能对应一个后端请求吗？比如我去请求一个页面，这个页面要请求多个后端接口，那我前端一个页面的多个请求分别为多个span是吗？

**Comment by peaksnail** [comment]
一个前端请求 可以对应多个后端请求啊，每个服务模块用span来标识，假设前端span-A，对应3个后端span-B,span-C span-D,那这四个span 要关联起来，通过两个点，一个是transactionId 来标识这四个span同属于一个请求，另一个是通过parentSpanId 和spanId，将调用的前后关系关联。比如对span-B来说，他的parentSpanId 就是span-A

**Comment by peaksnail** [comment]
接上面，这样的话 前端span-A 将会存储多个nextSpanId 指向 后端不同的Span-B，Span-C等。
同时对于之前提到的不支持async，实际是上支持了，我已找到具体原因，是因为没有将callback绑定到当前上下文导致的.下周修复.具体见  #9

**Comment by jiaojiaojiao** [comment]
多谢

**Comment by jiaojiaojiao** [comment]
哇哦，辛苦team

**Comment by peaksnail** [comment]
``` javascript
SpanRecorder.prototype.getNextSpanId = function getNextSpanId() {
    if (this.nextSpanId === undefined) {
        this.nextSpanId = SequenceNumberSingleton.getSequenceNumber();
    }
    return this.nextSpanId;
};
```
这里确实是bug,针对每一个后端请求应该是不同的nextSpanId。我上述解释是对的，但是代码是错的，抱歉，应该改为
``` javascript
SpanRecorder.prototype.getNextSpanId = function getNextSpanId() {
    this.nextSpanId = SequenceNumberSingleton.getSequenceNumber();
    return this.nextSpanId;
};
```

下周会进行测试，修复

**Comment by jiaojiaojiao** [comment]
好的，感谢
